#!/bin/bash

export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && . "$NVM_DIR/nvm.sh"  # This loads nvm

nvm install
nvm use

set -o xtrace
set -o nounset
set -o errexit

# Installing yarn
YARN_VERSION="1.3.2"
YARN_LOCATION="tools/${YARN_VERSION}"

if [ ! -d "$YARN_LOCATION" ]; then
        mkdir -p ${YARN_LOCATION}
        cd ${YARN_LOCATION}/
        wget -qO- https://github.com/yarnpkg/yarn/releases/download/v${YARN_VERSION}/yarn-v${YARN_VERSION}.tar.gz | tar zvx
        cd ../..
fi
PATH="$PATH:${YARN_LOCATION}/yarn-v${YARN_VERSION}/bin/"
yarn



################################################################################
#
# Build static assets for the project, files will now be found in public/
#
################################################################################

SCSS_DIR=assets/stylesheets

pushd $SCSS_DIR
../../node_modules/bower/bin/bower install
popd

yarn run "$@"
