#!/bin/bash
export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && . "$NVM_DIR/nvm.sh"  # This loads nvm
nvm use new

set -o xtrace
set -o nounset
set -o errexit

################################################################################
#
# Build static assets for the project, files will now be found in public/
#
################################################################################

JS_DIR=assets/javascripts
SCSS_DIR=assets/stylesheets

npm install

pushd $JS_DIR
../../node_modules/bower/bin/bower install
popd

pushd $SCSS_DIR
../../node_modules/bower/bin/bower install
popd

grunt "$@"
